# Creating `array`s from Existing Data 
* Creating an array with the **`array`** function 
* Argument is an `array` or other iterable
* Returns a new `array` containing the argument’s elements

In [ ]:
import numpy as np

In [ ]:
numbers = np.array([2, 3, 5, 7, 11])

In [ ]:
type(numbers)

numpy.ndarray

In [ ]:
numbers

array([ 2,  3,  5,  7, 11])

### Multidimensional Arguments

In [ ]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

# `array` Attributes 
* **attributes**  enable you to discover information about its structure and contents

In [ ]:
import numpy as np

In [ ]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [ ]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [ ]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

* NumPy does not display trailing 0s

### Determining an `array`’s Element Type

In [ ]:
integers.dtype

dtype('int32')

In [ ]:
floats.dtype

dtype('float64')

* For performance reasons, NumPy is written in the C programming language and uses C’s data types
* [Other NumPy types](https://docs.scipy.org/doc/numpy/user/basics.types.html)

### Determining an `array`’s Dimensions
* **`ndim`** contains an `array`’s number of dimensions 
* **`shape`** contains a _tuple_ specifying an `array`’s dimensions

In [ ]:
integers.ndim

2

In [ ]:
floats.ndim

1

In [ ]:
integers.shape

(2, 3)

In [ ]:
floats.shape

(5,)

### Determining an `array`’s Number of Elements and Element Size
* view an `array`’s total number of elements with **`size`** 
* view number of bytes required to store each element with **`itemsize`**

In [ ]:
integers.size

6

In [ ]:
integers.itemsize

4

In [ ]:
floats.size

5

In [ ]:
floats.itemsize

8

### Iterating through a Multidimensional `array`’s Elements


In [ ]:
for row in integers:
    for column in row:
        print(column, end='  ')
    print() 

1  2  3  
4  5  6  


* Iterate through a multidimensional `array` as if it were one-dimensional by using **`flat`**

In [ ]:
for i in integers.flat:
    print(i, end='  ')

1  2  3  4  5  6  

# Creating `array`s from Ranges 
* NumPy provides optimized functions for creating `array`s from ranges

### Creating Integer Ranges with `arange`

In [ ]:
import numpy as np

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

### Creating Floating-Point Ranges with `linspace` 
* Produce evenly spaced floating-point ranges with NumPy’s **`linspace`** function
* Ending value **is included** in the `array`

In [ ]:
np.linspace(0.0, 1.0, num=5)

### Reshaping an `array` 
* `array` method **`reshape`** transforms an array into different number of dimensions
* New shape must have the **same** number of elements as the original

In [ ]:
np.arange(1, 21).reshape(4, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

### Displaying Large `array`s 
* When displaying an `array`, if there are 1000 items or more, NumPy drops the middle rows, columns or both from the output

In [ ]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [ ]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])